name: Keep API Alive
on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 1 minute

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Base URL
        run: curl -s https://agrob-git-main-lalit-shelkars-projects.vercel.app > /dev/null
      
      - name: Ping fast2sms_verify.txt Route
        run: curl -s https://agrob-git-main-lalit-shelkars-projects.vercel.app/fast2sms_verify.txt > /dev/null
